export type Product = {
  id: string;
  /** Unique, auto-generated, e.g. BRK-00012 */
  itemCode: string;
  name: string;
  description: string;
  price: number;
  /** Uploaded photos as data URLs (first one is the main picture; empty = placeholder icon) */
  images: string[];
  category: string;
  brand: string;
  vehicleType: string;
  stock: number;
  createdAt: string;
};

/** What the "Add product" form provides – id, itemCode and createdAt are generated by the store. */
export type NewProduct = Omit<Product, 'id' | 'itemCode' | 'createdAt'>;
